import Head from 'next/head';
import Notice from '@/components/Notice';
import TopNav from '@/components/TopNav';
import MiddleNav from '@/components/MiddleNav';
import BottomStickyNav from '@/components/BottomStickyNav';
import SliderHeader from '@/components/SliderHeader';
import SliderFeature from '@/components/SliderFeature';
import FeaturedProducts from '@/components/FeaturedProducts';
import SaleBanner from '@/components/SaleBanner';
import CategoriesSlider from '@/components/CategoriesSlider';
import Services from '@/components/Services';
import ParallexPromo from '@/components/ParallexPromo';
import LatestNews from '@/components/LatestNews';
import BrandsMarquee from '@/components/BrandsMarquee';
import MobileBottomNav from '@/components/MobileBottomNav';
import "rsuite/dist/rsuite.min.css";
import 'swiper/css';
import "swiper/css/free-mode";
import Footer from '@/components/Footer';


export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='App relative'>
        <Notice />
        <TopNav />
        <MiddleNav />
        <BottomStickyNav />
        <SliderHeader />
        <SliderFeature />
        <FeaturedProducts />
        <SaleBanner />
        <CategoriesSlider />
        <Services />
        <ParallexPromo />
        <LatestNews />
        <BrandsMarquee />
        <Footer />
        <MobileBottomNav />
      </main>
    </>
  );
}
